---
- name: Install PostgreSQL on Debian based systems
  become: true
  apt:
    name: "{{ postgresql_ubuntu }}"
    state: present
  when: ansible_os_family == 'Debian'

- name: Install PostgreSQL on Red Hat based systems
  become: true
  yum:
    name: {{ postgresql_redhat }}
    state: present
  when: ansible_os_family == 'RedHat'
